// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGRKJaa2dpBb8nMiVb1Dm7CQeZRQuyHHQ',
    appId: '1:609693408487:web:3eb3997bc15cc4d61a1642',
    messagingSenderId: '609693408487',
    projectId: 'projectuas-13440',
    authDomain: 'projectuas-13440.firebaseapp.com',
    storageBucket: 'projectuas-13440.appspot.com',
    measurementId: 'G-K73TEX4G24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpTT7BMGZmDj-p2b8ClzFyOfAglPjuyxA',
    appId: '1:609693408487:android:347242002e8b637b1a1642',
    messagingSenderId: '609693408487',
    projectId: 'projectuas-13440',
    storageBucket: 'projectuas-13440.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABktkt0FTyDhHCLudpzgdD8XgLxmN8oGQ',
    appId: '1:609693408487:ios:3cb564fc224f0dc11a1642',
    messagingSenderId: '609693408487',
    projectId: 'projectuas-13440',
    storageBucket: 'projectuas-13440.appspot.com',
    iosBundleId: 'com.example.uasProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABktkt0FTyDhHCLudpzgdD8XgLxmN8oGQ',
    appId: '1:609693408487:ios:471d1cd452e19ba41a1642',
    messagingSenderId: '609693408487',
    projectId: 'projectuas-13440',
    storageBucket: 'projectuas-13440.appspot.com',
    iosBundleId: 'com.example.uasProject.RunnerTests',
  );
}
